name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run checks
        run: make check
